[build]
  functions = "netlify/functions"
  publish = "."

[functions]
  node_bundle = true

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Content-Security-Policy = "frame-ancestors 'none'"